development:
  clients:
    default:
      database: geosearch_with_mongodb_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: geosearch_with_mongodb_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1
        
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true
