development:
  clients:
    default:
      database: geosearch_with_mongodb_development
      hosts:
        - localhost:27017
        
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
