development:
  clients:
    default:
      database: geosearch_with_mongodb_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: geosearch_with_mongodb_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1

   development:
     clients:
       default:
         database: mongoid_dev
         hosts:
           - localhost:27017

        production:

production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  max_retries_on_connection_failure: 20
  persist_in_safe_mode: true
  skip_version_check: true
